import { StyleSheet } from "react-native";
export default StyleSheet.create({
	Screen: {
		backgroundColor: "#50A162",
		flex: 1,
	},
	Text1: {
		fontFamily: "Yellowtail_400Regular",
		fontSize: 96,
		marginTop: "15%",
		textAlign: "center",
		color: "#DBB364",
	},
	Text2: {
		fontSize: 18,
		fontFamily: "Poppins_400Regular",
		color: "#fff",
		textAlign: "center",
	},

	Text3: {
		fontFamily: "Poppins_400Regular",
		color: "#fff",
	},

	Text4: {
		fontFamily: "Moul_400Regular",
		color: "black",
		textAlign: "center",
		marginTop: "47%",
		fontSize: 16,
	},
	SignInText: {
		color: "#DBB364",
		fontFamily: "Poppins_500Medium",
	},
	Button: {
		backgroundColor: "#DBB364",
		alignItems: "center",
		height: "100%",
		borderRadius: 20,
	},
	Facebook: {
		backgroundColor: "#1877F2",
		height: "75%",
		width: "90%",
		marginLeft: "6%",
		borderRadius: 21,
		flexDirection: "row",
		alignItems: "center",
	},
	FacebookIcon: {
		marginLeft: "5%",
	},
	FacebookText: {
		color: "#fff",
		marginLeft: "6%",
		fontFamily: "Poppins_500Medium",
		fontSize: 15,
	},
	Google: {
		backgroundColor: "#FFFFFF",
		height: "75%",
		width: "90%",
		marginTop: "7%",
		marginLeft: "6%",
		borderRadius: 21,
		flexDirection: "row",
		alignItems: "center",
	},
	GoogleIcon: {
		marginLeft: "4%",
	},
	GoogleText: {
		color: "#000000A6",
		marginLeft: "3%",
		fontFamily: "Poppins_500Medium",
		fontSize: 15,
	},

	Apple: {
		backgroundColor: "#000000",
		height: "75%",
		width: "90%",
		marginTop: "7%",
		marginLeft: "6%",
		borderRadius: 21,
		flexDirection: "row",
		alignItems: "center",
	},
	AppleIcon: {
		marginLeft: "4%",
	},
	AppleText: {
		color: "#fff",
		marginLeft: "4%",
		fontFamily: "Poppins_500Medium",
		fontSize: 15,
	},
	TwitterIcon: {
		marginTop: "4%",
	},
	InstagramIcon: {
		marginLeft: "40%",
		marginTop: "4%",
	},
	item: {
		backgroundColor: "#DBB364",
		padding: 20,
		borderColor: "black",
		borderTopWidth: 1,
	},
	title: {
		color: "#fff",
		fontSize: 22,
		fontFamily: "Poppins_400Regular",
	},
	TextItem: {
		fontFamily: "Yellowtail_400Regular",
		fontSize: 96,
		marginTop: "10%",
		textAlign: "center",
		color: "#DBB364",
	},
	TopBar: {
		alignSelf: "center",
		borderBottomStartRadius: 15,
		borderBottomEndRadius: 15,
		width: "50%",
		backgroundColor: "#DBB364",
		borderWidth: 1,
		borderTopWidth: 0,
	},
	BarText: {
		fontSize: 35,
		textAlign: "center",
		color: "#fff",
	},
	LockButton: {
		backgroundColor: "#DBB364",
		width: "40%",
		alignSelf: "center",
		alignItems: "center",
		marginTop: "35%",
		borderWidth: 1,
		height: "20%",
	},

	ChangeButtonView: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: "40%",
		height: "15%",
		width: "85%",
		alignSelf: "center",
	},

	TextInput: {
		marginTop: "9%",
		backgroundColor: "#DBB364",
		width: "75%",
		padding: "5%",
		alignSelf: "center",
		borderRadius: 21,
		fontSize: 18,
		fontFamily: "Poppins_500Medium",
		color: "white",
	},
	AddButton: {
		backgroundColor: "#fff",
		alignSelf: "center",
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		height: "100%",
		width: "100%",
	},
	AddButtonView: {
		width: "35%",
		height: "8%",
		alignSelf: "center",
		marginTop: "15%",
		marginLeft: "15%",
		marginRight: "15%",
	},
	Add: {
		fontSize: 25,
		fontFamily: "Poppins_500Medium",
	},
	Success: {
		fontSize: 20,
		textAlign: "center",
		marginTop: "10%",
	},
	AddPhotoButton: {
		backgroundColor: "white",
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		minHeight: "10%",
		minWidth: "50%",
		marginTop: "10%",
	},
	DeleteButton: {
		backgroundColor: "white",
		minWidth: "15%",
		alignItems: "center",
		borderRadius: 21,
	},
	Delete: {
		fontSize: 25,
		fontFamily: "Poppins_500Medium",
	},
	TextInput2: {
		marginTop: "5%",
		backgroundColor: "#DBB364",
		width: "75%",
		padding: "5%",
		alignSelf: "center",
		borderRadius: 21,
		fontSize: 18,
		fontFamily: "Poppins_500Medium",
		color: "white",
	},
	AddProduct: {
		alignItems: "center",
		marginTop: "15%",
		backgroundColor: "white",
		width: "35%",
		alignSelf: "center",
		borderRadius: 21,
		height: "7%",
		justifyContent: "center",
	},
	ProductName: {
		textAlign: "center",
		marginTop: "5%",
		fontSize: 30,
		fontFamily: "Poppins_500Medium",
	},
	Photo: {
		marginTop: "8%",
		width: "90%",
		height: "50%",
		alignSelf: "center",
	},
	ProductButtons: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginTop: "15%",
		marginRight: "5%",
		marginLeft: "5%",
	},
	Update: {
		fontSize: 25,
		fontFamily: "Poppins_500Medium",
	},
	UpdateButton: {
		backgroundColor: "white",
		alignItems: "center",
		borderRadius: 21,
	},
	BackButton: {
		backgroundColor: "#fff",
		alignSelf: "center",
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		height: "25%",
		width: "50%",
		marginTop: "10%",
	},
});
